# Spring-boot/cloud application configuration.
#
# Here you can override the spring configuration provided by the Gateway
# by default.
#
# See here for the default provided configuration:
# https://github.com/georchestra/georchestra-gateway/blob/main/gateway/src/main/resources/application.yml

server:
  forward-headers-strategy: FRAMEWORK
  reactive:
    session:
      timeout: 1440m # 24h

spring:
  cloud:
    gateway:
      metrics.enabled: true
      default-filters:
      - SecureHeaders # add security-related HTTP headers to responses sent from the gateway to clients. See https://blog.appcanary.com/2017/http-security-headers.html
      - TokenRelay # propagates OAuth2 access tokens from incoming requests to downstream services
      - RemoveSecurityHeaders # removing incoming sec-* headers to prevent impresionation
      - AddSecHeaders # append resolved sec-* headers to proxied requests based on the currently authenticated user
      - PreserveHostHeader # ensure that the original Host header from the incoming HTTP request is preserved and passed along to the downstream service
      - ApplicationError # use gateway's custom error pages when a downstream request returns an error code
      - LoginParamRedirect # redirect to /login if the request contains a ?login query param and is not already authenticated
      - RemoveResponseHeader=X-Content-Type-Options # remove unwanted response header from downstream services
      - RemoveResponseHeader=X-Frame-Options # remove unwanted response header from downstream services
      filter:
        secure-headers:
          disable: # NOTE: header names must be lower-case
          - content-security-policy
          - x-frame-options
          - x-content-type-options
          referrer-policy: strict-origin
          enabled: true
          frame-options: SAMEORIGIN
          xss-protection-header: 0
          #content-security-policy: script-src 'self' 'unsafe-eval'; object-src 'self';

      # httpclient:
      #   pool:
      #     max-idle-time: 30000
      #     leasing-strategy: lifo
          # eviction-interval: 1000
        # connect-timeout: 30s
        # response-timeout: 30s